
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages
   '(all-the-icons cape consult-dir corfu dired-collapse dired-narrow
		   dired-ranger dired-subtree diredfl dirvish
		   doom-modeline doom-themes eglot-booster eldoc-box
		   embark-consult evil-args evil-collection
		   evil-escape evil-exchange evil-goggles
		   evil-indent-plus evil-lion evil-matchit
		   evil-multiedit evil-nerd-commenter evil-numbers
		   evil-snipe evil-surround evil-visualstar
		   flymake-diagnostic-at-point general marginalia
		   nerd-icons-completion nerd-icons-corfu
		   nerd-icons-dired orderless solaire-mode
		   treesit-auto treesit-fold vertico wgrep))
 '(package-vc-selected-packages
   '((eglot-booster :url "https://github.com/jdtsmith/eglot-booster"
		    :branch "master")
     (combobulate :url "https://github.com/mickeynp/combobulate.git"
		  :branch "master"))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(completions-annotations ((t (:foreground "#a89984" :italic t))))
 '(completions-first-difference ((t (:foreground "#fabd2f" :weight bold))))
 '(consult-bookmark ((t (:foreground "#d3869b"))))
 '(consult-buffer ((t (:foreground "#ebdbb2"))))
 '(consult-file ((t (:foreground "#8ec07c"))))
 '(consult-imenu-prefix ((t (:foreground "#7c6f64"))))
 '(consult-key ((t (:foreground "#fe8019"))))
 '(consult-line-number ((t (:foreground "#7c6f64"))))
 '(consult-line-number-prefix ((t (:foreground "#504945"))))
 '(consult-line-number-wrapped ((t (:foreground "#fb4934"))))
 '(consult-narrow-indicator ((t (:foreground "#fabd2f"))))
 '(consult-preview-cursor ((t (:background "#fe8019"))))
 '(consult-preview-error ((t (:foreground "#fb4934"))))
 '(consult-preview-insertion ((t (:background "#b8bb26" :foreground "#282828"))))
 '(consult-preview-line ((t (:background "#504945"))))
 '(consult-preview-match ((t (:background "#d3869b" :foreground "#282828"))))
 '(consult-separator ((t (:foreground "#7c6f64"))))
 '(corfu-annotations ((t (:foreground "#9aa5ce" :italic t))))
 '(corfu-bar ((t (:background "#bb9af7"))))
 '(corfu-border ((t (:background "#565f89"))))
 '(corfu-current ((t (:background "#414868" :foreground "#c0caf5" :weight bold))))
 '(corfu-default ((t (:background "#24283b" :foreground "#c0caf5"))))
 '(corfu-deprecated ((t (:foreground "#565f89" :strike-through t))))
 '(corfu-popupinfo ((t (:background "#24283b" :foreground "#c0caf5"))))
 '(corfu-popupinfo-documentation ((t (:foreground "#9aa5ce" :italic t))))
 '(dired-collapse-face ((t (:foreground "#83a598" :weight normal))))
 '(dired-directory ((t (:foreground "#83a598" :weight bold))))
 '(dired-filter-date ((t (:foreground "#d3869b"))))
 '(dired-filter-extension ((t (:foreground "#b8bb26"))))
 '(dired-filter-mode ((t (:foreground "#8ec07c"))))
 '(dired-filter-name ((t (:foreground "#83a598"))))
 '(dired-filter-size ((t (:foreground "#fe8019"))))
 '(dired-filter-stack ((t (:foreground "#fabd2f"))))
 '(dired-flagged ((t (:foreground "#fb4934" :background "#3c3836"))))
 '(dired-header ((t (:foreground "#fabd2f" :weight bold))))
 '(dired-ignored ((t (:foreground "#928374"))))
 '(dired-marked ((t (:foreground "#fb4934" :weight bold))))
 '(dired-narrow-blink ((t (:foreground "#fabd2f" :background "#504945"))))
 '(dired-narrow-match ((t (:foreground "#b8bb26" :weight bold))))
 '(dired-narrow-rejected ((t (:foreground "#928374" :strike-through t))))
 '(dired-perm-write ((t (:foreground "#b8bb26"))))
 '(dired-special ((t (:foreground "#d3869b"))))
 '(dired-subtree-depth-1-face ((t (:background "#282828"))))
 '(dired-subtree-depth-2-face ((t (:background "#3c3836"))))
 '(dired-subtree-depth-3-face ((t (:background "#282828"))))
 '(dired-subtree-depth-4-face ((t (:background "#3c3836"))))
 '(dired-subtree-depth-5-face ((t (:background "#282828"))))
 '(dired-subtree-depth-6-face ((t (:background "#3c3836"))))
 '(dired-symlink ((t (:foreground "#8ec07c"))))
 '(dired-warning ((t (:foreground "#fe8019" :weight bold))))
 '(dirvish-emerge-group-separator ((t (:foreground "#928374"))))
 '(dirvish-emerge-group-title ((t (:foreground "#fabd2f" :weight bold))))
 '(dirvish-file-size ((t (:foreground "#a89984"))))
 '(dirvish-file-time ((t (:foreground "#a89984"))))
 '(dirvish-free-space ((t (:foreground "#8ec07c"))))
 '(dirvish-git-commit-author ((t (:foreground "#83a598"))))
 '(dirvish-git-commit-message ((t (:foreground "#bdae93"))))
 '(dirvish-hl-line ((t (:background "#3c3836"))))
 '(dirvish-index-number ((t (:foreground "#fe8019"))))
 '(dirvish-path-separator ((t (:foreground "#928374"))))
 '(dirvish-sort-indicator ((t (:foreground "#b8bb26"))))
 '(dirvish-subtree-guide ((t (:foreground "#928374"))))
 '(dirvish-yank-line ((t (:background "#504945"))))
 '(doom-modeline-checker-error ((t (:foreground "#fb4934" :weight bold))))
 '(doom-modeline-checker-info ((t (:foreground "#83a598" :weight bold))))
 '(doom-modeline-checker-success ((t (:foreground "#b8bb26" :weight bold))))
 '(doom-modeline-checker-warning ((t (:foreground "#fabd2f" :weight bold))))
 '(embark-collect-group-separator ((t (:foreground "#7c6f64"))))
 '(embark-collect-group-title ((t (:foreground "#d3869b" :weight bold))))
 '(embark-collect-marked ((t (:background "#504945" :foreground "#ebdbb2"))))
 '(embark-keybinding ((t (:foreground "#fe8019" :weight bold))))
 '(marginalia-archive ((t (:foreground "#9ece6a"))))
 '(marginalia-char ((t (:foreground "#ff9e64"))))
 '(marginalia-date ((t (:foreground "#7dcfff"))))
 '(marginalia-documentation ((t (:foreground "#9aa5ce" :italic t))))
 '(marginalia-file-name ((t (:foreground "#c0caf5"))))
 '(marginalia-file-owner ((t (:foreground "#bb9af7"))))
 '(marginalia-file-priv-dir ((t (:foreground "#7aa2f7"))))
 '(marginalia-file-priv-exec ((t (:foreground "#9ece6a"))))
 '(marginalia-file-priv-link ((t (:foreground "#7dcfff"))))
 '(marginalia-file-priv-read ((t (:foreground "#ff9e64"))))
 '(marginalia-file-priv-write ((t (:foreground "#f7768e"))))
 '(marginalia-function ((t (:foreground "#7aa2f7"))))
 '(marginalia-key ((t (:foreground "#ff9e64"))))
 '(marginalia-lighter ((t (:foreground "#565f89"))))
 '(marginalia-list ((t (:foreground "#7dcfff"))))
 '(marginalia-mode ((t (:foreground "#bb9af7"))))
 '(marginalia-modified ((t (:foreground "#e0af68"))))
 '(marginalia-null ((t (:foreground "#565f89"))))
 '(marginalia-number ((t (:foreground "#ff9e64"))))
 '(marginalia-size ((t (:foreground "#9ece6a"))))
 '(marginalia-string ((t (:foreground "#9ece6a"))))
 '(marginalia-symbol ((t (:foreground "#bb9af7"))))
 '(marginalia-true ((t (:foreground "#9ece6a"))))
 '(marginalia-type ((t (:foreground "#7aa2f7"))))
 '(marginalia-value ((t (:foreground "#c0caf5"))))
 '(marginalia-variable ((t (:foreground "#7dcfff"))))
 '(marginalia-version ((t (:foreground "#9ece6a"))))
 '(minibuffer-prompt ((t (:foreground "#83a598" :weight bold))))
 '(nerd-icons-dired-audio-face ((t (:foreground "#d3869b"))))
 '(nerd-icons-dired-compressed-face ((t (:foreground "#fabd2f"))))
 '(nerd-icons-dired-dir-face ((t (:foreground "#83a598" :weight bold))))
 '(nerd-icons-dired-executable-face ((t (:foreground "#b8bb26"))))
 '(nerd-icons-dired-file-face ((t (:foreground "#ebdbb2"))))
 '(nerd-icons-dired-image-face ((t (:foreground "#fe8019"))))
 '(nerd-icons-dired-symlink-face ((t (:foreground "#8ec07c"))))
 '(nerd-icons-dired-video-face ((t (:foreground "#fb4934"))))
 '(orderless-match-face-0 ((t (:foreground "#bb9af7" :weight bold))))
 '(orderless-match-face-1 ((t (:foreground "#7aa2f7" :weight bold))))
 '(orderless-match-face-2 ((t (:foreground "#9ece6a" :weight bold))))
 '(orderless-match-face-3 ((t (:foreground "#e0af68" :weight bold))))
 '(vertico-current ((t (:background "#414868" :foreground "#c0caf5" :weight bold))))
 '(vertico-group-separator ((t (:foreground "#565f89"))))
 '(vertico-group-title ((t (:foreground "#bb9af7" :weight bold))))
 '(vertico-multiline ((t (:foreground "#7aa2f7"))))
 '(wgrep-done-face ((t (:foreground "#b8bb26" :weight bold))))
 '(wgrep-face ((t (:background "#504945" :foreground "#ebdbb2"))))
 '(wgrep-file-face ((t (:foreground "#83a598" :weight bold))))
 '(wgrep-reject-face ((t (:foreground "#fb4934" :weight bold))))
 '(which-key-command-description-face ((t (:foreground "#ebdbb2"))))
 '(which-key-description-face ((t (:foreground "#ebdbb2"))))
 '(which-key-docstring-face ((t (:foreground "#928374" :slant italic))))
 '(which-key-group-description-face ((t (:foreground "#d3869b" :weight bold))))
 '(which-key-highlighted-command-face ((t (:foreground "#83a598" :weight bold :underline t))))
 '(which-key-key-face ((t (:foreground "#fe8019" :weight bold))))
 '(which-key-local-map-description-face ((t (:foreground "#fabd2f"))))
 '(which-key-note-face ((t (:foreground "#8ec07c"))))
 '(which-key-separator-face ((t (:foreground "#504945"))))
 '(which-key-special-key-face ((t (:foreground "#fb4934" :weight bold)))))
